sudo: false

language: ruby

rvm:
  - 2.0.0

cache: bundler
script: bundle exec middleman build --clean
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: docs.catenae-api.surge.sh
